workspace = { members = ["sql-builder-def", "sql-builder-meta-macros"] }
[package]
name = "sql-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
sqlx = "0.8.0"
sql-builder-macros = { path = "./sql-builder-macros" }
itertools = "0.13.0"
futures-core = "0.3.30"
